language: android
android:
  components:
    - build-tools-20

notifications:
  email: true

before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

# Let's try to build...
#install: ./gradlew clean build

script: ./gradlew clean build